[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
edition = "2021"
name = "revme"
keywords = ["ethereum", "evm"]
license = "MIT"
repository = "https://github.com/bluealloy/revm"
description = "Rust Ethereum Virtual Machine Executable"
version = "0.3.1"

[dependencies]
hash-db = "0.15"
hex = "0.4"
hashbrown = "0.14"
indicatif = "0.17"
microbench = "0.5"
plain_hasher = "0.2"
revm = { package = "fluentbase-revm", git = "https://github.com/fluentlabs-xyz/fluentbase", branch = "devel", default-features = false, features = [
    "ethersdb",
    "std",
    "serde-json",
    "c-kzg",
] }
revm-original = { package = "revm", path = "../../crates/revm", default-features = false, features = [
    "ethersdb",
    "std",
    "serde-json",
    "c-kzg",
] }
#revm = { package = "revm", path = "../../../../other/revm/crates/revm", version = "7.2.0", default-features = false, features = [
#    "ethersdb",
#    "std",
#    "serde-json",
#    "c-kzg",
#] }
#revm-oiginal-primitives = { package = "revm-primitives", path = "../../../../other/revm/crates/primitives", default-features = false, features = [
#    "ethersdb",
#    "std",
#    "serde-json",
#    "c-kzg",
#] }
#revm-oiginal = { package = "revme", git = "https://github.com/bluealloy/revm", version = "7.2.0", default-features = false, features = [
#    "ethersdb",
#    "std",
#    "serde-json",
#    "c-kzg",
#] }
#revm-oiginal-primitives = { package = "revm-primitives", git = "https://github.com/bluealloy/revm.git", version = "8.0.0", default-features = false }
fluentbase-types = { path = "../../../fluentbase/crates/types", default-features = false }
#revm = { path = "../../crates/revm", version = "7.2.0", default-features = false, features = [
#    "ethersdb",
#    "std",
#    "serde-json",
#    "c-kzg",
#] }
alloy-rlp = { version = "0.3", default-features = false, features = [
    "arrayvec",
    "derive",
] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
structopt = "0.3"
thiserror = "1.0"
triehash = "0.8"
walkdir = "2.5"
k256 = { version = "0.13.3", features = ["ecdsa"] }
