name: Publish to crates.io

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-release
        run: cargo install cargo-release --locked

      - name: Dry run (check which crates will be published)
        run: |
          cargo release publish \
            --workspace \
            --exclude revme \
            --exclude custom_precompile_journal \
            --no-confirm \
            -v

      - name: Publish crates to crates.io
        if: success()
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo release publish \
            --workspace \
            --exclude revme \
            --exclude custom_precompile_journal \
            --no-confirm \
            --execute
